"""initial SP Telegram license schema"""
from alembic import op
import sqlalchemy as sa

revision="0001_license_schema";down_revision=None;branch_labels=None;depends_on=None

def upgrade():
    op.create_table("plans",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("code",sa.String(32),nullable=False,unique=True),sa.Column("name",sa.String(80),nullable=False),sa.Column("price_monthly",sa.Numeric(8,2),nullable=False),sa.Column("device_limit",sa.Integer(),nullable=False),sa.Column("max_accounts",sa.Integer()),sa.Column("max_source_groups",sa.Integer()),sa.Column("max_target_groups",sa.Integer()),sa.Column("max_member_pool",sa.Integer()),sa.Column("max_templates",sa.Integer()),sa.Column("features_json",sa.JSON(),nullable=False),sa.Column("is_active",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False))
    op.create_index("ix_plans_code","plans",["code"],unique=True)
    op.create_table("licenses",sa.Column("id",sa.String(36),primary_key=True),sa.Column("license_key_hash",sa.String(64),nullable=False,unique=True),sa.Column("license_key_prefix",sa.String(32),nullable=False),sa.Column("plan_id",sa.Integer(),sa.ForeignKey("plans.id",ondelete="RESTRICT"),nullable=False),sa.Column("status",sa.String(32),nullable=False),sa.Column("starts_at",sa.DateTime(timezone=True),nullable=False),sa.Column("expires_at",sa.DateTime(timezone=True),nullable=False),sa.Column("customer_reference",sa.String(120)),sa.Column("notes",sa.Text()),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.Column("suspended_at",sa.DateTime(timezone=True)),sa.Column("revoked_at",sa.DateTime(timezone=True)))
    op.create_index("ix_licenses_key_hash","licenses",["license_key_hash"],unique=True);op.create_index("ix_licenses_status","licenses",["status"]);op.create_index("ix_licenses_expires","licenses",["expires_at"])
    op.create_table("license_devices",sa.Column("id",sa.String(36),primary_key=True),sa.Column("license_id",sa.String(36),sa.ForeignKey("licenses.id",ondelete="CASCADE"),nullable=False),sa.Column("device_id_hash",sa.String(64),nullable=False),sa.Column("device_name",sa.String(160),nullable=False),sa.Column("platform",sa.String(80),nullable=False),sa.Column("app_version",sa.String(40),nullable=False),sa.Column("activated_at",sa.DateTime(timezone=True),nullable=False),sa.Column("last_seen_at",sa.DateTime(timezone=True),nullable=False),sa.Column("deactivated_at",sa.DateTime(timezone=True)),sa.Column("is_active",sa.Boolean(),nullable=False),sa.UniqueConstraint("license_id","device_id_hash",name="uq_license_device"))
    op.create_index("ix_license_devices_license","license_devices",["license_id"]);op.create_index("ix_license_devices_active","license_devices",["is_active"])
    op.create_table("license_events",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("license_id",sa.String(36),sa.ForeignKey("licenses.id",ondelete="SET NULL")),sa.Column("event_type",sa.String(64),nullable=False),sa.Column("message",sa.Text()),sa.Column("metadata_json",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_index("ix_license_events_license","license_events",["license_id"]);op.create_index("ix_license_events_type","license_events",["event_type"]);op.create_index("ix_license_events_created","license_events",["created_at"])

def downgrade():
    op.drop_table("license_events");op.drop_table("license_devices");op.drop_table("licenses");op.drop_table("plans")
