# Design tokens for SP Telegram

# Colors
BASE_BACKGROUND = "#0F0B1E"
BASE_SURFACE = "#171129"
BASE_ELEVATED = "#1D1636"
BASE_PANEL = "#252525"
BASE_CARD = "#2D2D2D"

# Text colors
TEXT_PRIMARY = "#F4F1FF"
TEXT_SECONDARY = "#A9A3CC"
TEXT_MUTED = "#6F6896"
TEXT_DISABLED = "#3A2E5C"

# Accent colors
ACCENT_PRIMARY = "#FFB6C1"
ACCENT_SECONDARY = "#DDA0DD"
ACCENT_SUCCESS = "#32CD32"
ACCENT_WARNING = "#FFD700"
ACCENT_DANGER = "#FF69B4"
ACCENT_INFO = "#22D3EE"

# Borders
BORDER_PRIMARY = "#3A2E5C"
BORDER_SECONDARY = "#5A4B8C"

# Shadows
SHADOW_SMALL = "0 2px 4px rgba(0, 0, 0, 0.1)"
SHADOW_MEDIUM = "0 4px 6px rgba(0, 0, 0, 0.15)"
SHADOW_LARGE = "0 6px 8px rgba(0, 0, 0, 0.2)"

# Spacing
SPACING_XS = "4px"
SPACING_SM = "8px"
SPACING_MD = "12px"
SPACING_LG = "16px"
SPACING_XL = "24px"

# Border radius
RADIUS_SM = "4px"
RADIUS_MD = "8px"
RADIUS_LG = "12px"
RADIUS_XL = "16px"

# Typography
FONT_FAMILY = "Segoe UI, Noto Sans Khmer, sans-serif"
FONT_SIZE_SM = "11px"
FONT_SIZE_MD = "13px"
FONT_SIZE_LG = "16px"
FONT_SIZE_XL = "20px"
FONT_WEIGHT_REGULAR = "400"
FONT_WEIGHT_MEDIUM = "550"
FONT_WEIGHT_SEMIBOLD = "650"
FONT_WEIGHT_BOLD = "700"

# Sidebar dimensions
SIDEBAR_EXPANDED = 240
SIDEBAR_COLLAPSED = 60

# Light theme colors
LIGHT_BASE_BACKGROUND = "#F3F6FC"
LIGHT_BASE_SURFACE = "#FFFFFF"
LIGHT_BASE_ELEVATED = "#F9F9F9"
LIGHT_BASE_PANEL = "#F0F0F0"
LIGHT_BASE_CARD = "#E8E8E8"

LIGHT_TEXT_PRIMARY = "#1F2937"
LIGHT_TEXT_SECONDARY = "#64748B"
LIGHT_TEXT_MUTED = "#94A3B8"
LIGHT_TEXT_DISABLED = "#DCE4F2"

LIGHT_ACCENT_PRIMARY = "#FFB6C1"
LIGHT_ACCENT_SECONDARY = "#DDA0DD"
LIGHT_ACCENT_SUCCESS = "#32CD32"
LIGHT_ACCENT_WARNING = "#FFD700"
LIGHT_ACCENT_DANGER = "#FF69B4"
LIGHT_ACCENT_INFO = "#22D3EE"

LIGHT_BORDER_PRIMARY = "#F0E9F6"
LIGHT_BORDER_SECONDARY = "#E6D9F2"

# Status colors
STATUS_OK = "#32CD32"
STATUS_WARNING = "#FFD700"
STATUS_ERROR = "#FF69B4"
STATUS_MUTED = "#94A3B8"

# Light status colors
LIGHT_STATUS_OK = "#0B9D6C"
LIGHT_STATUS_WARNING = "#B45309"
LIGHT_STATUS_ERROR = "#E11D48"
LIGHT_STATUS_MUTED = "#94A3B8"

# Page layout
PAGE_PADDING = 20
TABLE_HEADER_HEIGHT = 40
TABLE_ROW_HEIGHT = 36

# Status color mappings
STATUS_COLORS = {
    "OK": STATUS_OK,
    "WARNING": STATUS_WARNING,
    "ERROR": STATUS_ERROR,
    "MUTED": STATUS_MUTED,
}

LIGHT_STATUS_COLORS = {
    "OK": LIGHT_STATUS_OK,
    "WARNING": LIGHT_STATUS_WARNING,
    "ERROR": LIGHT_STATUS_ERROR,
    "MUTED": LIGHT_STATUS_MUTED,
}