from __future__ import annotations

try:
    from enum import StrEnum
except ImportError:
    from enum import Enum
    class StrEnum(str, Enum):
        def __str__(self): return str(self.value)


class FeatureKey(StrEnum):
    ACCOUNT_MANAGER = "FEATURE_ACCOUNT_MANAGER"
    ACCOUNT_SESSIONS = "FEATURE_ACCOUNT_SESSIONS"
    ACCOUNT_HEALTH = "FEATURE_ACCOUNT_HEALTH"
    RESTRICTIONS = "FEATURE_RESTRICTIONS"
    GROUP_MANAGER = "FEATURE_GROUP_MANAGER"
    GROUP_RESOLVER = "FEATURE_GROUP_RESOLVER"
    GROUP_PERMISSIONS = "FEATURE_GROUP_PERMISSIONS"
    GROUP_SYNC = "FEATURE_GROUP_SYNC"
    MEMBER_POOL = "FEATURE_MEMBER_POOL"
    MEMBER_SYNC = "FEATURE_MEMBER_SYNC"
    MEMBER_TAGS = "FEATURE_MEMBER_TAGS"
    ADVANCED_MEMBER_FILTERS = "FEATURE_ADVANCED_MEMBER_FILTERS"
    TARGET_MEMBER_STATUS = "FEATURE_TARGET_MEMBER_STATUS"
    TARGET_PREPARATION = "FEATURE_TARGET_PREPARATION"
    INVITE_LINK = "FEATURE_INVITE_LINK"
    TARGET_MEMBER_SYNC = "FEATURE_TARGET_MEMBER_SYNC"
    DIRECT_MEMBER_INVITE = "FEATURE_DIRECT_MEMBER_INVITE"
    BLACKLIST = "FEATURE_BLACKLIST"
    CSV_IMPORT = "FEATURE_CSV_IMPORT"
    CSV_EXPORT = "FEATURE_CSV_EXPORT"
    DASHBOARD = "FEATURE_DASHBOARD"
    LOGS = "FEATURE_LOGS"
    BASIC_ALERTS = "FEATURE_BASIC_ALERTS"
    CAMPAIGNS = "FEATURE_CAMPAIGNS"
    MEDIA_POSTING = "FEATURE_MEDIA_POSTING"
    MULTI_MESSAGE = "FEATURE_MULTI_MESSAGE"
    TEMPLATES = "FEATURE_TEMPLATES"
    SEND_NOW = "FEATURE_SEND_NOW"
    SCHEDULE_ONCE = "FEATURE_SCHEDULE_ONCE"
    RECURRING_SCHEDULE = "FEATURE_RECURRING_SCHEDULE"
    CONTENT_CALENDAR = "FEATURE_CONTENT_CALENDAR"
    CAMPAIGN_PREVIEW = "FEATURE_CAMPAIGN_PREVIEW"
    CAMPAIGN_PREFLIGHT = "FEATURE_CAMPAIGN_PREFLIGHT"
    ADVANCED_JOBS = "FEATURE_ADVANCED_JOBS"
    ACCOUNT_MONITORING = "FEATURE_ACCOUNT_MONITORING"
    GROUP_MONITORING = "FEATURE_GROUP_MONITORING"
    SAFE_RECOVERY = "FEATURE_SAFE_RECOVERY"
    ADVANCED_ALERTS = "FEATURE_ADVANCED_ALERTS"
    BASIC_CAMPAIGN_ANALYTICS = "FEATURE_BASIC_CAMPAIGN_ANALYTICS"
    ADVANCED_ANALYTICS = "FEATURE_ADVANCED_ANALYTICS"
    FULL_OPERATIONS = "FEATURE_FULL_OPERATIONS"
    MANUAL_BACKUP = "FEATURE_MANUAL_BACKUP"
    RESTORE = "FEATURE_RESTORE"
    AUTO_BACKUP = "FEATURE_AUTO_BACKUP"
    SECURITY_AUDIT = "FEATURE_SECURITY_AUDIT"
    APP_LOCK = "FEATURE_APP_LOCK"
    PRIVACY_MODE = "FEATURE_PRIVACY_MODE"
    ADVANCED_DIAGNOSTICS = "FEATURE_ADVANCED_DIAGNOSTICS"
    SUPPORT_BUNDLE = "FEATURE_SUPPORT_BUNDLE"


class LimitKey(StrEnum):
    MAX_ACCOUNTS = "MAX_ACCOUNTS"
    MAX_SOURCE_GROUPS = "MAX_SOURCE_GROUPS"
    MAX_TARGET_GROUPS = "MAX_TARGET_GROUPS"
    MAX_MEMBER_POOL = "MAX_MEMBER_POOL"
    MAX_TEMPLATES = "MAX_TEMPLATES"
    MAX_DEVICES = "MAX_DEVICES"


# Backward-friendly constants for concise imports throughout controller/service gates.
for _name, _member in FeatureKey.__members__.items(): globals()[f"FEATURE_{_name}"] = _member
for _name, _member in LimitKey.__members__.items(): globals()[_name] = _member
